# Generated by Django 6.1.1 on 2026-09-29 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_notificationpreference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('NEW_CONSENT', 'New Consent Request'), ('REPORT_READY', 'Report Ready'), ('REQUEST_APPROVED', 'Request Approved'), ('REQUEST_REJECTED', 'Request Rejected'), ('REQUEST_POSTPONED', 'Request Postponed'), ('REFERRAL_ACCEPTED', 'Referral Accepted'), ('REFERRAL_REJECTED', 'Referral Rejected'), ('REFERRAL_CREATED', 'Referral Created'), ('TRANSFER_COMPLETED', 'Transfer Completed'), ('STATUS_UPDATE', 'Status Update'), ('REQUEST_COMPLETED', 'Request Completed'), ('ACCESS_REQUEST', 'Access Request'), ('EMERGENCY_ACCESS', 'Emergency Access'), ('GENERAL', 'General')], max_length=30),
        ),
    ]
