# Generated by Django 6.1.1 on 2026-09-12 14:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admissions', '0001_initial'),
        ('ai_insights', '0001_initial'),
        ('hospitals', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('required_department_type', models.CharField(max_length=30)),
                ('priority', models.CharField(default='HIGH', max_length=20)),
                ('reason', models.TextField()),
                ('current_condition_summary', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('CONDITIONAL', 'Conditional Accept')], default='PENDING', max_length=20)),
                ('response_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('ai_summary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_insights.aiinsight')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referrals_created', to=settings.AUTH_USER_MODEL)),
                ('from_admission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referrals', to='admissions.admission')),
                ('from_hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referrals_sent', to='hospitals.hospital')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referrals', to='patients.patientprofile')),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals_responded', to=settings.AUTH_USER_MODEL)),
                ('to_hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referrals_received', to='hospitals.hospital')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ambulance_arranged', models.BooleanField(default=False)),
                ('checklist', models.JSONField(blank=True, default=dict)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('new_admission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='admissions.admission')),
                ('referral', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transfer', to='referrals.referral')),
            ],
        ),
    ]
