# Generated by Django 6.1.1 on 2026-09-12 14:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIInsight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('insight_type', models.CharField(choices=[('EMERGENCY_SUMMARY', 'Emergency Patient Summary'), ('TIMELINE', 'Medical Timeline'), ('REFERRAL_SUMMARY', 'Referral Summary'), ('HANDOVER', 'Doctor-to-Doctor Handover'), ('MISSING_INFO', 'Missing Information Alert'), ('CONFLICT_ALERT', 'Record Conflict Alert')], max_length=30)),
                ('content_text', models.TextField()),
                ('status', models.CharField(choices=[('GENERATED', 'Generated'), ('FLAGGED_CONFLICT', 'Flagged: Conflict Present'), ('FLAGGED_INCOMPLETE', 'Flagged: Missing Information')], default='GENERATED', max_length=30)),
                ('generated_by_service', models.CharField(default='lifelink-mock-ai-v1', max_length=50)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='AIReference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(max_length=40)),
                ('source_object_id', models.CharField(blank=True, max_length=64)),
                ('source_description', models.CharField(max_length=255)),
            ],
        ),
    ]
