# Generated by Django 6.1.1 on 2026-09-12 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_insights', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aiinsight',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_insights', to='patients.patientprofile'),
        ),
        migrations.AddField(
            model_name='aiinsight',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aireference',
            name='insight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='ai_insights.aiinsight'),
        ),
    ]
