import uuid

from django.conf import settings
from django.db import models


class InsightType(models.TextChoices):
    EMERGENCY_SUMMARY = 'EMERGENCY_SUMMARY', 'Emergency Patient Summary'
    TIMELINE = 'TIMELINE', 'Medical Timeline'
    REFERRAL_SUMMARY = 'REFERRAL_SUMMARY', 'Referral Summary'
    HANDOVER = 'HANDOVER', 'Doctor-to-Doctor Handover'
    MISSING_INFO = 'MISSING_INFO', 'Missing Information Alert'
    CONFLICT_ALERT = 'CONFLICT_ALERT', 'Record Conflict Alert'


class InsightStatus(models.TextChoices):
    GENERATED = 'GENERATED', 'Generated'
    FLAGGED_CONFLICT = 'FLAGGED_CONFLICT', 'Flagged: Conflict Present'
    FLAGGED_INCOMPLETE = 'FLAGGED_INCOMPLETE', 'Flagged: Missing Information'


class AIInsight(models.Model):
    """
    Section 28/29/50/51 — AI output. HARD RULE enforced at the service layer
    (apps/ai_insights/engine.py), not just documentation: this model only
    ever stores text that was generated by walking real DB records. There is
    no code path that lets free-text be saved here without AIReference rows
    pointing at real source records.
    """
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    patient = models.ForeignKey('patients.PatientProfile', on_delete=models.CASCADE, related_name='ai_insights')
    insight_type = models.CharField(max_length=30, choices=InsightType.choices)
    content_text = models.TextField()
    status = models.CharField(max_length=30, choices=InsightStatus.choices, default=InsightStatus.GENERATED)
    generated_by_service = models.CharField(max_length=50, default='lifelink-mock-ai-v1')
    generated_at = models.DateTimeField(auto_now_add=True)
    requested_by = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, blank=True, on_delete=models.SET_NULL)

    class Meta:
        ordering = ['-generated_at']


class AIReference(models.Model):
    """Every meaningful claim in an AIInsight must trace back to one of
    these (section 29). `source_description` is always human-readable
    ("Discharge Summary, ABC Hospital, 12 Aug 2023") even when a direct FK
    to the source record isn't available."""
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    insight = models.ForeignKey(AIInsight, on_delete=models.CASCADE, related_name='references')
    source_type = models.CharField(max_length=40)  # e.g. "MedicalHistoryEntry", "Document", "Medication"
    source_object_id = models.CharField(max_length=64, blank=True)
    source_description = models.CharField(max_length=255)
