# Generated by Django 6.1.1 on 2026-09-12 14:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admissions', '0001_initial'),
        ('documents', '0001_initial'),
        ('hospitals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientIDCounter',
            fields=[
                ('id', models.PositiveIntegerField(default=1, primary_key=True, serialize=False)),
                ('last_value', models.PositiveIntegerField(default=100000)),
            ],
        ),
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lifelink_patient_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('U', 'Unspecified')], default='U', max_length=1)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('blood_group_verification', models.CharField(choices=[('SELF_REPORTED', 'Self-Reported'), ('VERIFIED', 'Verified'), ('PENDING_VERIFICATION', 'Pending Verification'), ('CONFLICT', 'Conflict Detected'), ('SYSTEM_GENERATED', 'System-Generated')], default='PENDING_VERIFICATION', max_length=30)),
                ('is_unclaimed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_patient_profiles', to='hospitals.hospital')),
                ('created_by_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_patient_profiles', to='hospitals.staffprofile')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('dosage', models.CharField(blank=True, max_length=100)),
                ('frequency', models.CharField(blank=True, max_length=100)),
                ('start_date', models.DateField()),
                ('stop_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('STOPPED', 'Stopped'), ('COMPLETED', 'Completed Course')], default='ACTIVE', max_length=20)),
                ('source', models.CharField(choices=[('SELF_REPORTED', 'Self-Reported'), ('FAMILY_REPORTED', 'Family-Reported'), ('HOSPITAL_ENTERED', 'Hospital-Entered'), ('DOCTOR_ENTERED', 'Doctor-Entered'), ('DOCUMENT_UPLOAD', 'Uploaded Document'), ('SYSTEM_GENERATED', 'System-Generated'), ('AI_GENERATED', 'AI-Generated Summary')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medications', to='admissions.admission')),
                ('prescribing_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescribed_medications', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='patients.patientprofile')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='MedicalHistoryEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('DIAGNOSIS', 'Diagnosis'), ('CHRONIC_CONDITION', 'Chronic Condition'), ('SURGERY', 'Major Surgery/Procedure'), ('ADMISSION_SUMMARY', 'Admission Summary'), ('LAB_RESULT', 'Important Lab Result'), ('IMAGING_RESULT', 'Important Imaging Result')], max_length=30)),
                ('description', models.TextField()),
                ('event_date', models.DateField()),
                ('source', models.CharField(choices=[('SELF_REPORTED', 'Self-Reported'), ('FAMILY_REPORTED', 'Family-Reported'), ('HOSPITAL_ENTERED', 'Hospital-Entered'), ('DOCTOR_ENTERED', 'Doctor-Entered'), ('DOCUMENT_UPLOAD', 'Uploaded Document'), ('SYSTEM_GENERATED', 'System-Generated'), ('AI_GENERATED', 'AI-Generated Summary')], max_length=30)),
                ('verification_status', models.CharField(choices=[('SELF_REPORTED', 'Self-Reported'), ('VERIFIED', 'Verified'), ('PENDING_VERIFICATION', 'Pending Verification'), ('CONFLICT', 'Conflict Detected'), ('SYSTEM_GENERATED', 'System-Generated')], default='PENDING_VERIFICATION', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('originating_admission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_entries', to='admissions.admission')),
                ('originating_hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospitals.hospital')),
                ('source_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.document')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_entries', to='patients.patientprofile')),
            ],
            options={
                'ordering': ['-event_date'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('relationship', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to='patients.patientprofile')),
            ],
        ),
        migrations.CreateModel(
            name='BloodGroupReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('source', models.CharField(choices=[('SELF_REPORTED', 'Self-Reported'), ('FAMILY_REPORTED', 'Family-Reported'), ('HOSPITAL_ENTERED', 'Hospital-Entered'), ('DOCTOR_ENTERED', 'Doctor-Entered'), ('DOCUMENT_UPLOAD', 'Uploaded Document'), ('SYSTEM_GENERATED', 'System-Generated'), ('AI_GENERATED', 'AI-Generated Summary')], max_length=30)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('source_admission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blood_group_reports', to='admissions.admission')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood_group_reports', to='patients.patientprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('substance', models.CharField(max_length=150)),
                ('severity', models.CharField(choices=[('MILD', 'Mild'), ('MODERATE', 'Moderate'), ('SEVERE', 'Severe')], default='MODERATE', max_length=20)),
                ('source', models.CharField(choices=[('SELF_REPORTED', 'Self-Reported'), ('FAMILY_REPORTED', 'Family-Reported'), ('HOSPITAL_ENTERED', 'Hospital-Entered'), ('DOCTOR_ENTERED', 'Doctor-Entered'), ('DOCUMENT_UPLOAD', 'Uploaded Document'), ('SYSTEM_GENERATED', 'System-Generated'), ('AI_GENERATED', 'AI-Generated Summary')], max_length=30)),
                ('verification_status', models.CharField(choices=[('SELF_REPORTED', 'Self-Reported'), ('VERIFIED', 'Verified'), ('PENDING_VERIFICATION', 'Pending Verification'), ('CONFLICT', 'Conflict Detected'), ('SYSTEM_GENERATED', 'System-Generated')], default='PENDING_VERIFICATION', max_length=30)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allergies', to='patients.patientprofile')),
            ],
        ),
        migrations.CreateModel(
            name='FamilyRelationship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relationship_type', models.CharField(max_length=50)),
                ('access_level', models.CharField(choices=[('FULL_REPRESENTATIVE', 'Full Emergency Representative'), ('UPDATES_ONLY', 'Family Updates Only'), ('LIMITED', 'Limited Access')], default='UPDATES_ONLY', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('family_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_links', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_links', to='patients.patientprofile')),
            ],
            options={
                'unique_together': {('patient', 'family_user')},
            },
        ),
    ]
