# Generated by Django 6.1.1 on 2026-09-13 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='familyrelationship',
            options={'ordering': ['-created_at']},
        ),
    ]
