# Generated by Django 6.1.1 on 2026-09-15 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_familyrelationship_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allergy',
            name='verification_status',
            field=models.CharField(choices=[('SELF_REPORTED', 'Self-Reported'), ('VERIFIED', 'Verified'), ('PENDING_VERIFICATION', 'Pending Verification'), ('CONFLICT', 'Conflict Detected'), ('REJECTED', 'Rejected'), ('SYSTEM_GENERATED', 'System-Generated')], default='PENDING_VERIFICATION', max_length=30),
        ),
        migrations.AlterField(
            model_name='medicalhistoryentry',
            name='verification_status',
            field=models.CharField(choices=[('SELF_REPORTED', 'Self-Reported'), ('VERIFIED', 'Verified'), ('PENDING_VERIFICATION', 'Pending Verification'), ('CONFLICT', 'Conflict Detected'), ('REJECTED', 'Rejected'), ('SYSTEM_GENERATED', 'System-Generated')], default='PENDING_VERIFICATION', max_length=30),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='blood_group_verification',
            field=models.CharField(choices=[('SELF_REPORTED', 'Self-Reported'), ('VERIFIED', 'Verified'), ('PENDING_VERIFICATION', 'Pending Verification'), ('CONFLICT', 'Conflict Detected'), ('REJECTED', 'Rejected'), ('SYSTEM_GENERATED', 'System-Generated')], default='PENDING_VERIFICATION', max_length=30),
        ),
    ]
