# Generated by Django 6.1.1 on 2026-09-12 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admissions', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admissions', to='patients.patientprofile'),
        ),
        migrations.AddField(
            model_name='dischargesummary',
            name='admission',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discharge_summary', to='admissions.admission'),
        ),
        migrations.AddField(
            model_name='dischargesummary',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='doctornote',
            name='admission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_notes', to='admissions.admission'),
        ),
        migrations.AddField(
            model_name='doctornote',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='doctor_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nursingnote',
            name='admission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nursing_notes', to='admissions.admission'),
        ),
        migrations.AddField(
            model_name='nursingnote',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nursing_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='admission',
            index=models.Index(fields=['hospital', 'status'], name='admissions__hospita_ca537a_idx'),
        ),
    ]
