# Generated by Django 6.1.1 on 2026-09-12 14:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('department_type', models.CharField(choices=[('GENERAL', 'General / OPD'), ('RADIOLOGY', 'Radiology'), ('LABORATORY', 'Laboratory'), ('PHARMACY', 'Pharmacy'), ('OT', 'Operation Theatre'), ('WARD', 'Ward / Nursing'), ('BILLING', 'Billing'), ('INSURANCE', 'Insurance Desk'), ('MANAGEMENT', 'Hospital Management / Care Coordination'), ('ADMIN', 'Hospital Admin')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='hospitals.hospital')),
            ],
            options={
                'unique_together': {('hospital', 'department_type', 'name')},
            },
        ),
        migrations.CreateModel(
            name='HospitalCapacity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resource_type', models.CharField(choices=[('ICU_BED', 'ICU Bed'), ('GENERAL_BED', 'General Bed'), ('OT_SLOT', 'OT Slot'), ('CARDIOLOGIST', 'Cardiologist Availability'), ('VENTILATOR', 'Ventilator')], max_length=30)),
                ('total', models.PositiveIntegerField(default=0)),
                ('available', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capacities', to='hospitals.hospital')),
            ],
            options={
                'unique_together': {('hospital', 'resource_type')},
            },
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('staff_role', models.CharField(choices=[('DOCTOR', 'Doctor'), ('NURSE', 'Nurse'), ('TECHNICIAN', 'Technician'), ('PHARMACIST', 'Pharmacist'), ('COORDINATOR', 'Care Coordinator'), ('BILLING_CLERK', 'Billing Clerk'), ('INSURANCE_OFFICER', 'Insurance Officer'), ('ADMIN', 'Hospital Admin')], max_length=30)),
                ('employee_id', models.CharField(max_length=40)),
                ('job_title', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='hospitals.department')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='hospitals.hospital')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('hospital', 'employee_id')},
            },
        ),
    ]
