# Generated by Django 6.1.1 on 2026-09-12 14:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admissions', '0001_initial'),
        ('consents', '0001_initial'),
        ('documents', '0001_initial'),
        ('hospitals', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_type', models.CharField(choices=[('CT_SCAN', 'CT Scan'), ('MRI', 'MRI'), ('XRAY', 'X-Ray'), ('BLOOD_TEST', 'Blood Test'), ('PATHOLOGY', 'Pathology'), ('MEDICATION', 'Medication Order'), ('SURGERY', 'Surgery / Procedure'), ('INSURANCE_APPROVAL', 'Insurance Approval'), ('PAYMENT', 'Payment'), ('CONSULTATION', 'Specialist Consultation'), ('DOCUMENT_VERIFICATION', 'Document Verification'), ('GENERIC_TASK', 'Internal Task')], max_length=30)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('EMERGENCY', 'Emergency')], default='NORMAL', max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('PENDING', 'Pending'), ('APPROVAL_REQUIRED', 'Approval Required'), ('APPROVED', 'Approved / Awaiting Action'), ('READY', 'Ready'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('POSTPONED', 'Postponed'), ('CANCELLED', 'Cancelled'), ('BLOCKED', 'Blocked'), ('REJECTED', 'Rejected')], default='REQUESTED', max_length=30)),
                ('requires_consent', models.BooleanField(default=False)),
                ('requires_payment', models.BooleanField(default=False)),
                ('is_family_visible', models.BooleanField(default=False)),
                ('postpone_or_reject_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_requests', to='admissions.admission')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to=settings.AUTH_USER_MODEL)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_requests', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_requests', to=settings.AUTH_USER_MODEL)),
                ('linked_consent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_requests', to='consents.consentrequest')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_requests', to='patients.patientprofile')),
                ('result_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='documents.document')),
                ('target_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='hospitals.department')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StatusTransition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(max_length=30)),
                ('to_status', models.CharField(max_length=30)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='workflow.servicerequest')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['status', 'target_department'], name='workflow_se_status_17df09_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['patient', 'status'], name='workflow_se_patient_55e211_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['admission', 'status'], name='workflow_se_admissi_20d597_idx'),
        ),
    ]
