# Generated by Django 6.1.1 on 2026-09-12 14:27

import apps.documents.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=apps.documents.models.patient_document_path)),
                ('doc_type', models.CharField(choices=[('LAB_REPORT', 'Lab Report'), ('IMAGING_REPORT', 'Imaging Report'), ('DISCHARGE_SUMMARY', 'Discharge Summary'), ('PRESCRIPTION', 'Prescription'), ('CONSENT_FORM', 'Consent Form'), ('INSURANCE_DOCUMENT', 'Insurance Document'), ('IDENTITY_DOCUMENT', 'Identity Document'), ('OTHER', 'Other')], max_length=30)),
                ('version', models.PositiveIntegerField(default=1)),
                ('source', models.CharField(blank=True, max_length=30)),
                ('verification_status', models.CharField(default='PENDING_VERIFICATION', max_length=30)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('admission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='admissions.admission')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
